### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by EvilSlime** [PeachesMLG/MobCoins#1]
[06:45:31] [Server thread/ERROR]: Could not load 'plugins/MobCoins.jar' in folder 'plugins'org.bukkit.plugin.InvalidPluginException: No public constructor at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:79) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.IllegalAccessException: Class org.bukkit.plugin.java.PluginClassLoader can not access a member of class com.peaches.mobcoins.Main with modifiers "public" at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[?:1.8.0_141] at java.lang.Class.newInstance(Class.java:436) ~[?:1.8.0_141] at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:77) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] ... 7 more

**Comment by PeachesMLG** [comment]
my mistake, forgot to set the modifier to public should be fixed now

**Comment by EvilSlime** [comment]
Where is the new version?

**Comment by PeachesMLG** [comment]
on spigot
